.TH "Hardware/obj/Debug Directory Reference" 3 "Sat Sep 24 2022" "Version beta" "WolfNet 6502 WorkBench Computer Emulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Hardware/obj/Debug Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fB\&.NETFramework,Version=v4\&.8\&.AssemblyAttributes\&.cs\fP"
.br
.in -1c
