.TH "Emulator/obj/x86/Publish Directory Reference" 3 "Wed Sep 28 2022" "Version beta" "WolfNet 6502 WorkBench Computer Emulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Emulator/obj/x86/Publish Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fB\&.NETFramework,Version=v4\&.8\&.AssemblyAttributes\&.cs\fP"
.br
.ti -1c
.RI "file \fBApp\&.g\&.cs\fP"
.br
.ti -1c
.RI "file \fBApp\&.g\&.i\&.cs\fP"
.br
.ti -1c
.RI "file \fBEmulator_Content\&.g\&.cs\fP"
.br
.ti -1c
.RI "file \fBEmulator_Content\&.g\&.i\&.cs\fP"
.br
.ti -1c
.RI "file \fBGeneratedInternalTypeHelper\&.g\&.cs\fP"
.br
.ti -1c
.RI "file \fBGeneratedInternalTypeHelper\&.g\&.i\&.cs\fP"
.br
.ti -1c
.RI "file \fBMainWindow\&.g\&.cs\fP"
.br
.ti -1c
.RI "file \fBMainWindow\&.g\&.i\&.cs\fP"
.br
.ti -1c
.RI "file \fBSaveFile\&.g\&.cs\fP"
.br
.ti -1c
.RI "file \fBSaveFile\&.g\&.i\&.cs\fP"
.br
.ti -1c
.RI "file \fBSettings\&.g\&.cs\fP"
.br
.ti -1c
.RI "file \fBSettings\&.g\&.i\&.cs\fP"
.br
.in -1c
