.TH "Emulator.Model.RomFileModel" 3 "Wed Sep 28 2022" "Version beta" "WolfNet 6502 WorkBench Computer Emulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Emulator.Model.RomFileModel \- The \fBModel\fP used when Loading a Program\&.   

.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "byte[][] \fBRom\fP\fC [get, set]\fP"
.br
.RI "The Program Converted into Hex\&.  "
.ti -1c
.RI "byte \fBRomBanks\fP\fC [get, set]\fP"
.br
.RI "The path of the Program that was loaded\&.  "
.ti -1c
.RI "int \fBRomBankSize\fP\fC [get, set]\fP"
.br
.RI "The name of the Program that was loaded\&.  "
.ti -1c
.RI "string \fBRomFileName\fP\fC [get, set]\fP"
.br
.RI "The name of the Program that was loaded\&.  "
.ti -1c
.RI "string \fBRomFilePath\fP\fC [get, set]\fP"
.br
.RI "The path of the Program that was loaded\&.  "
.in -1c
.SH "Detailed Description"
.PP 
The \fBModel\fP used when Loading a Program\&.  
.PP
Definition at line \fB6\fP of file \fBRomFileModel\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "byte [][] Emulator\&.Model\&.RomFileModel\&.Rom\fC [get]\fP, \fC [set]\fP"

.PP
The Program Converted into Hex\&.  
.PP
Definition at line \fB11\fP of file \fBRomFileModel\&.cs\fP\&.
.PP
.nf
11 { get; set; }
.fi
.SS "byte Emulator\&.Model\&.RomFileModel\&.RomBanks\fC [get]\fP, \fC [set]\fP"

.PP
The path of the Program that was loaded\&.  
.PP
Definition at line \fB16\fP of file \fBRomFileModel\&.cs\fP\&.
.PP
.nf
16 { get; set; }
.fi
.SS "int Emulator\&.Model\&.RomFileModel\&.RomBankSize\fC [get]\fP, \fC [set]\fP"

.PP
The name of the Program that was loaded\&.  
.PP
Definition at line \fB21\fP of file \fBRomFileModel\&.cs\fP\&.
.PP
.nf
21 { get; set; }
.fi
.SS "string Emulator\&.Model\&.RomFileModel\&.RomFileName\fC [get]\fP, \fC [set]\fP"

.PP
The name of the Program that was loaded\&.  
.PP
Definition at line \fB26\fP of file \fBRomFileModel\&.cs\fP\&.
.PP
.nf
26 { get; set; }
.fi
.SS "string Emulator\&.Model\&.RomFileModel\&.RomFilePath\fC [get]\fP, \fC [set]\fP"

.PP
The path of the Program that was loaded\&.  
.PP
Definition at line \fB31\fP of file \fBRomFileModel\&.cs\fP\&.
.PP
.nf
31 { get; set; }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for WolfNet 6502 WorkBench Computer Emulator from the source code\&.
