.TH "Emulator.MemoryVisual" 3 "Wed Sep 28 2022" "Version beta" "WolfNet 6502 WorkBench Computer Emulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Emulator.MemoryVisual \- Interaction logic for Window1\&.xaml   

.SH SYNOPSIS
.br
.PP
.PP
Inherits System\&.Windows\&.Window, System\&.Windows\&.Window, System\&.Windows\&.Markup\&.IComponentConnector, System\&.Windows\&.Window, System\&.Windows\&.Markup\&.IComponentConnector, System\&.Windows\&.Window, System\&.Windows\&.Markup\&.IComponentConnector, System\&.Windows\&.Window, and System\&.Windows\&.Markup\&.IComponentConnector\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMemoryVisual\fP ()"
.br
.ti -1c
.RI "void \fBInitializeComponent\fP ()"
.br
.RI "InitializeComponent  "
.ti -1c
.RI "void \fBInitializeComponent\fP ()"
.br
.RI "InitializeComponent  "
.ti -1c
.RI "void \fBInitializeComponent\fP ()"
.br
.RI "InitializeComponent  "
.ti -1c
.RI "void \fBInitializeComponent\fP ()"
.br
.RI "InitializeComponent  "
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void System\&.Windows\&.Markup\&.IComponentConnector\&. \fBConnect\fP (int connectionId, object target)"
.br
.ti -1c
.RI "void System\&.Windows\&.Markup\&.IComponentConnector\&. \fBConnect\fP (int connectionId, object target)"
.br
.ti -1c
.RI "void System\&.Windows\&.Markup\&.IComponentConnector\&. \fBConnect\fP (int connectionId, object target)"
.br
.ti -1c
.RI "void System\&.Windows\&.Markup\&.IComponentConnector\&. \fBConnect\fP (int connectionId, object target)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "bool \fB_contentLoaded\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Interaction logic for Window1\&.xaml  

\fBMemoryVisual\fP  
.PP
Definition at line \fB8\fP of file \fBMemoryVisual\&.xaml\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Emulator\&.MemoryVisual\&.MemoryVisual ()\fC [inline]\fP"

.PP
Definition at line \fB10\fP of file \fBMemoryVisual\&.xaml\&.cs\fP\&.
.PP
.nf
11         {
12             InitializeComponent();
13         }
.fi
.SH "Member Function Documentation"
.PP 
.SS "void System\&.Windows\&.Markup\&.IComponentConnector\&. Emulator\&.MemoryVisual\&.Connect (int connectionId, object target)\fC [inline]\fP, \fC [private]\fP"

.PP
Definition at line \fB93\fP of file \fBMemoryVisual\&.g\&.cs\fP\&.
.PP
.nf
93                                                                                                 {
94             switch (connectionId)
95             {
96             case 1:
97             this\&.MemoryMap = ((System\&.Windows\&.Controls\&.DataGrid)(target));
98             return;
99             case 2:
100             this\&.CurrentPage = ((System\&.Windows\&.Controls\&.TextBox)(target));
101             return;
102             case 3:
103             this\&.CurrentPageText = ((System\&.Windows\&.Controls\&.TextBlock)(target));
104             return;
105             }
106             this\&._contentLoaded = true;
107         }
.fi
.SS "void System\&.Windows\&.Markup\&.IComponentConnector\&. Emulator\&.MemoryVisual\&.Connect (int connectionId, object target)\fC [inline]\fP, \fC [private]\fP"

.PP
Definition at line \fB93\fP of file \fBMemoryVisual\&.g\&.i\&.cs\fP\&.
.PP
.nf
93                                                                                                 {
94             switch (connectionId)
95             {
96             case 1:
97             this\&.MemoryMap = ((System\&.Windows\&.Controls\&.DataGrid)(target));
98             return;
99             case 2:
100             this\&.CurrentPage = ((System\&.Windows\&.Controls\&.TextBox)(target));
101             return;
102             case 3:
103             this\&.CurrentPageText = ((System\&.Windows\&.Controls\&.TextBlock)(target));
104             return;
105             }
106             this\&._contentLoaded = true;
107         }
.fi
.SS "void System\&.Windows\&.Markup\&.IComponentConnector\&. Emulator\&.MemoryVisual\&.Connect (int connectionId, object target)\fC [inline]\fP, \fC [private]\fP"

.PP
Definition at line \fB93\fP of file \fBMemoryVisual\&.g\&.cs\fP\&.
.PP
.nf
93                                                                                                 {
94             switch (connectionId)
95             {
96             case 1:
97             this\&.MemoryMap = ((System\&.Windows\&.Controls\&.DataGrid)(target));
98             return;
99             case 2:
100             this\&.CurrentPage = ((System\&.Windows\&.Controls\&.TextBox)(target));
101             return;
102             case 3:
103             this\&.CurrentPageText = ((System\&.Windows\&.Controls\&.TextBlock)(target));
104             return;
105             }
106             this\&._contentLoaded = true;
107         }
.fi
.SS "void System\&.Windows\&.Markup\&.IComponentConnector\&. Emulator\&.MemoryVisual\&.Connect (int connectionId, object target)\fC [inline]\fP, \fC [private]\fP"

.PP
Definition at line \fB93\fP of file \fBMemoryVisual\&.g\&.i\&.cs\fP\&.
.PP
.nf
93                                                                                                 {
94             switch (connectionId)
95             {
96             case 1:
97             this\&.MemoryMap = ((System\&.Windows\&.Controls\&.DataGrid)(target));
98             return;
99             case 2:
100             this\&.CurrentPage = ((System\&.Windows\&.Controls\&.TextBox)(target));
101             return;
102             case 3:
103             this\&.CurrentPageText = ((System\&.Windows\&.Controls\&.TextBlock)(target));
104             return;
105             }
106             this\&._contentLoaded = true;
107         }
.fi
.SS "void Emulator\&.MemoryVisual\&.InitializeComponent ()\fC [inline]\fP"

.PP
InitializeComponent  
.PP
Definition at line \fB73\fP of file \fBMemoryVisual\&.g\&.cs\fP\&.
.PP
.nf
73                                           {
74             if (_contentLoaded) {
75                 return;
76             }
77             _contentLoaded = true;
78             System\&.Uri resourceLocater = new System\&.Uri("/Emulator;component/memoryvisual\&.xaml", System\&.UriKind\&.Relative);
79             
80             #line 1 "\&.\&.\\&.\&.\\&.\&.\MemoryVisual\&.xaml"
81             System\&.Windows\&.Application\&.LoadComponent(this, resourceLocater);
82             
83             #line default
84             #line hidden
85         }
.fi
.SS "void Emulator\&.MemoryVisual\&.InitializeComponent ()\fC [inline]\fP"

.PP
InitializeComponent  
.PP
Definition at line \fB73\fP of file \fBMemoryVisual\&.g\&.i\&.cs\fP\&.
.PP
.nf
73                                           {
74             if (_contentLoaded) {
75                 return;
76             }
77             _contentLoaded = true;
78             System\&.Uri resourceLocater = new System\&.Uri("/Emulator;component/memoryvisual\&.xaml", System\&.UriKind\&.Relative);
79             
80             #line 1 "\&.\&.\\&.\&.\\&.\&.\MemoryVisual\&.xaml"
81             System\&.Windows\&.Application\&.LoadComponent(this, resourceLocater);
82             
83             #line default
84             #line hidden
85         }
.fi
.SS "void Emulator\&.MemoryVisual\&.InitializeComponent ()\fC [inline]\fP"

.PP
InitializeComponent  
.PP
Definition at line \fB73\fP of file \fBMemoryVisual\&.g\&.cs\fP\&.
.PP
.nf
73                                           {
74             if (_contentLoaded) {
75                 return;
76             }
77             _contentLoaded = true;
78             System\&.Uri resourceLocater = new System\&.Uri("/Emulator;component/memoryvisual\&.xaml", System\&.UriKind\&.Relative);
79             
80             #line 1 "\&.\&.\\&.\&.\\&.\&.\MemoryVisual\&.xaml"
81             System\&.Windows\&.Application\&.LoadComponent(this, resourceLocater);
82             
83             #line default
84             #line hidden
85         }
.fi
.SS "void Emulator\&.MemoryVisual\&.InitializeComponent ()\fC [inline]\fP"

.PP
InitializeComponent  
.PP
Definition at line \fB73\fP of file \fBMemoryVisual\&.g\&.i\&.cs\fP\&.
.PP
.nf
73                                           {
74             if (_contentLoaded) {
75                 return;
76             }
77             _contentLoaded = true;
78             System\&.Uri resourceLocater = new System\&.Uri("/Emulator;component/memoryvisual\&.xaml", System\&.UriKind\&.Relative);
79             
80             #line 1 "\&.\&.\\&.\&.\\&.\&.\MemoryVisual\&.xaml"
81             System\&.Windows\&.Application\&.LoadComponent(this, resourceLocater);
82             
83             #line default
84             #line hidden
85         }
.fi
.SH "Member Data Documentation"
.PP 
.SS "bool Emulator\&.MemoryVisual\&._contentLoaded\fC [private]\fP"

.PP
Definition at line \fB66\fP of file \fBMemoryVisual\&.g\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for WolfNet 6502 WorkBench Computer Emulator from the source code\&.
