.TH "Emulator.Model.BreakpointType" 3 "Wed Sep 28 2022" "Version beta" "WolfNet 6502 WorkBench Computer Emulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Emulator.Model.BreakpointType \- The Type of \fBBreakpoint\fP   

.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static List< string > \fBAllTypes\fP"
.br
.RI "A Listing of all of the Current Types  "
.ti -1c
.RI "const string \fBProgramCounterType\fP = 'Program Counter'"
.br
.RI "The ProgamCounter \fBBreakpoint\fP Type  "
.ti -1c
.RI "const string \fBNumberOfCycleType\fP = 'Number of Cycles'"
.br
.RI "The CycleCount \fBBreakpoint\fP Type  "
.in -1c
.SH "Detailed Description"
.PP 
The Type of \fBBreakpoint\fP  
.PP
Definition at line \fB8\fP of file \fBBreakpointType\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "List<string> Emulator\&.Model\&.BreakpointType\&.AllTypes\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
= new List<string>
            {
                ProgramCounterType,
                NumberOfCycleType
            }
.fi
.PP
A Listing of all of the Current Types  
.PP
Definition at line \fB13\fP of file \fBBreakpointType\&.cs\fP\&.
.SS "const string Emulator\&.Model\&.BreakpointType\&.NumberOfCycleType = 'Number of Cycles'\fC [static]\fP"

.PP
The CycleCount \fBBreakpoint\fP Type  
.PP
Definition at line \fB27\fP of file \fBBreakpointType\&.cs\fP\&.
.SS "const string Emulator\&.Model\&.BreakpointType\&.ProgramCounterType = 'Program Counter'\fC [static]\fP"

.PP
The ProgamCounter \fBBreakpoint\fP Type  
.PP
Definition at line \fB22\fP of file \fBBreakpointType\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for WolfNet 6502 WorkBench Computer Emulator from the source code\&.
