.TH "Emulator.IClosable" 3 "Sat Sep 24 2022" "Version beta" "WolfNet 6502 WorkBench Computer Emulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Emulator.IClosable
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBEmulator\&.MainWindow\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBClose\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB9\fP of file \fBIClosable\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Emulator\&.IClosable\&.Close ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for WolfNet 6502 WorkBench Computer Emulator from the source code\&.
