.TH "Emulator.Model" 3 "Sat Sep 24 2022" "Version beta" "WolfNet 6502 WorkBench Computer Emulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Emulator.Model
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBreakpoint\fP"
.br
.RI "A Representation of a \fBBreakpoint\fP  "
.ti -1c
.RI "class \fBBreakpointType\fP"
.br
.RI "The Type of \fBBreakpoint\fP  "
.ti -1c
.RI "class \fBMemoryRowModel\fP"
.br
.RI "A \fBModel\fP of a Single Page of memory  "
.ti -1c
.RI "class \fBOutputLog\fP"
.br
.RI "The \fBOutputLog\fP \fBModel\fP\&. Used by the outputlog grid to show a history of operations performed by the CPU  "
.ti -1c
.RI "class \fBRomFileModel\fP"
.br
.RI "The \fBModel\fP used when Loading a Program\&.  "
.ti -1c
.RI "class \fBSettingsModel\fP"
.br
.RI "\fBModel\fP that contains the required information needed to save the current settings to disk  "
.ti -1c
.RI "class \fBStateFileModel\fP"
.br
.RI "\fBModel\fP that contains the required information needed to save the current state of the processor to disk  "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for WolfNet 6502 WorkBench Computer Emulator from the source code\&.
