.TH "Emulator.ViewModel.SettingsViewModel" 3 "Wed Sep 28 2022" "Version beta" "WolfNet 6502 WorkBench Computer Emulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Emulator.ViewModel.SettingsViewModel \- The \fBViewModel\fP Used by the SaveFileView   

.SH SYNOPSIS
.br
.PP
.PP
Inherits ViewModelBase\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSettingsViewModel\fP ()"
.br
.RI "Instantiates a new instance of the \fBSettingsViewModel\fP\&. This is used by the IOC to create the default instance\&.  "
.ti -1c
.RI "\fBSettingsViewModel\fP (\fBSettingsModel\fP settingsModel)"
.br
.RI "Instantiates a new instance of the \fBSettingsViewModel\fP  "
.ti -1c
.RI "void \fBUpdatePortList\fP ()"
.br
.RI "Updates PortList with the COM ports available to the computer  "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "RelayCommand \fBApplyCommand\fP\fC [get, set]\fP"
.br
.RI "The Relay Command called when saving a file  "
.ti -1c
.RI "RelayCommand \fBCloseCommand\fP\fC [get, set]\fP"
.br
.RI "The Relay Command called when closing a file  "
.ti -1c
.RI "bool \fBApplyEnabled\fP\fC [get]\fP"
.br
.RI "Tells the UI that that a file has been selected and can be saved\&.  "
.ti -1c
.RI "ObservableCollection< string > \fBPortList\fP\fC [get]\fP"
.br
.RI "Creates a new instance of PortList, the list of all COM ports available to the computer  "
.ti -1c
.RI "static string \fBComPortSelection\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "static \fBSettingsModel\fP \fBSettingsModel\fP\fC [get, set]\fP"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBApply\fP ()"
.br
.in -1c
.SS "Static Private Member Functions"

.in +1c
.ti -1c
.RI "static void \fBClose\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "readonly ObservableCollection< string > \fB_PortList\fP = new ObservableCollection<string>()"
.br
.in -1c
.SH "Detailed Description"
.PP 
The \fBViewModel\fP Used by the SaveFileView  
.PP
Definition at line \fB14\fP of file \fBSettingsViewModel\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Emulator\&.ViewModel\&.SettingsViewModel\&.SettingsViewModel ()\fC [inline]\fP"

.PP
Instantiates a new instance of the \fBSettingsViewModel\fP\&. This is used by the IOC to create the default instance\&.  
.PP
Definition at line \fB48\fP of file \fBSettingsViewModel\&.cs\fP\&.
.PP
.nf
49         {
50 
51         }
.fi
.SS "Emulator\&.ViewModel\&.SettingsViewModel\&.SettingsViewModel (\fBSettingsModel\fP settingsModel)\fC [inline]\fP"

.PP
Instantiates a new instance of the \fBSettingsViewModel\fP  
.PP
\fBParameters\fP
.RS 4
\fIsettingsModel\fP The SettingsFileModel to be serialized to a file
.RE
.PP

.PP
Definition at line \fB57\fP of file \fBSettingsViewModel\&.cs\fP\&.
.PP
.nf
58         {
59             ApplyCommand = new RelayCommand(Apply);
60             CloseCommand = new RelayCommand(Close);
61             ComPortSelection = settingsModel\&.ComPortName;
62 
63             UpdatePortList();
64         }
.fi
.SH "Member Function Documentation"
.PP 
.SS "void Emulator\&.ViewModel\&.SettingsViewModel\&.Apply ()\fC [inline]\fP, \fC [private]\fP"

.PP
Definition at line \fB81\fP of file \fBSettingsViewModel\&.cs\fP\&.
.PP
.nf
82         {
83             Messenger\&.Default\&.Send(new NotificationMessage<SettingsModel>(new SettingsModel
84             {
85                 SettingsVersionMajor = Versioning\&.SettingsFile\&.Major,
86                 SettingsVersionMinor = Versioning\&.SettingsFile\&.Minor,
87                 SettingsVersionBuild = Versioning\&.SettingsFile\&.Build,
88                 SettingsVersionRevision = Versioning\&.SettingsFile\&.Revision,
89                 ComPortName = ComPortSelection,
90             }, "SettingsApplied"));
91             Messenger\&.Default\&.Send(new NotificationMessage("CloseSettingsWindow"));
92         }
.fi
.SS "static void Emulator\&.ViewModel\&.SettingsViewModel\&.Close ()\fC [inline]\fP, \fC [static]\fP, \fC [private]\fP"

.PP
Definition at line \fB94\fP of file \fBSettingsViewModel\&.cs\fP\&.
.PP
.nf
95         {
96             Messenger\&.Default\&.Send(new NotificationMessage("CloseSettingsWindow"));
97         }
.fi
.SS "void Emulator\&.ViewModel\&.SettingsViewModel\&.UpdatePortList ()\fC [inline]\fP"

.PP
Updates PortList with the COM ports available to the computer  
.PP
Definition at line \fB69\fP of file \fBSettingsViewModel\&.cs\fP\&.
.PP
.nf
70         {
71             PortList\&.Clear();
72             foreach (string s in SerialPort\&.GetPortNames())
73             {
74                 PortList\&.Add(s);
75             }
76             RaisePropertyChanged("PortList");
77         }
.fi
.SH "Member Data Documentation"
.PP 
.SS "readonly ObservableCollection<string> Emulator\&.ViewModel\&.SettingsViewModel\&._PortList = new ObservableCollection<string>()\fC [private]\fP"

.PP
Definition at line \fB37\fP of file \fBSettingsViewModel\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "RelayCommand Emulator\&.ViewModel\&.SettingsViewModel\&.ApplyCommand\fC [get]\fP, \fC [set]\fP"

.PP
The Relay Command called when saving a file  
.PP
Definition at line \fB20\fP of file \fBSettingsViewModel\&.cs\fP\&.
.PP
.nf
20 { get; set; }
.fi
.SS "bool Emulator\&.ViewModel\&.SettingsViewModel\&.ApplyEnabled\fC [get]\fP"

.PP
Tells the UI that that a file has been selected and can be saved\&.  
.PP
Definition at line \fB30\fP of file \fBSettingsViewModel\&.cs\fP\&.
.PP
.nf
30 { get { return !string\&.IsNullOrEmpty(Emulator\&.FileLocations\&.SettingsFile); } }
.fi
.SS "RelayCommand Emulator\&.ViewModel\&.SettingsViewModel\&.CloseCommand\fC [get]\fP, \fC [set]\fP"

.PP
The Relay Command called when closing a file  
.PP
Definition at line \fB25\fP of file \fBSettingsViewModel\&.cs\fP\&.
.PP
.nf
25 { get; set; }
.fi
.SS "string Emulator\&.ViewModel\&.SettingsViewModel\&.ComPortSelection\fC [static]\fP, \fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB39\fP of file \fBSettingsViewModel\&.cs\fP\&.
.PP
.nf
39 { get; set; }
.fi
.SS "ObservableCollection<string> Emulator\&.ViewModel\&.SettingsViewModel\&.PortList\fC [get]\fP"

.PP
Creates a new instance of PortList, the list of all COM ports available to the computer  
.PP
Definition at line \fB36\fP of file \fBSettingsViewModel\&.cs\fP\&.
.PP
.nf
36 { get { return _PortList; } }
.fi
.SS "\fBSettingsModel\fP Emulator\&.ViewModel\&.SettingsViewModel\&.SettingsModel\fC [static]\fP, \fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB40\fP of file \fBSettingsViewModel\&.cs\fP\&.
.PP
.nf
40 { get; set; }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for WolfNet 6502 WorkBench Computer Emulator from the source code\&.
