.TH "Emulator" 3 "Wed Sep 28 2022" "Version beta" "WolfNet 6502 WorkBench Computer Emulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Emulator
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBModel\fP"
.br
.ti -1c
.RI "namespace \fBViewModel\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBApp\fP"
.br
.RI "Interaction logic for App\&.xaml  "
.ti -1c
.RI "class \fBExitCodes\fP"
.br
.ti -1c
.RI "interface \fBIClosable\fP"
.br
.ti -1c
.RI "class \fBMainWindow\fP"
.br
.RI "Interaction logic for MainWindow\&.xaml  "
.ti -1c
.RI "class \fBMemoryVisual\fP"
.br
.RI "Interaction logic for Window1\&.xaml  "
.ti -1c
.RI "class \fBMultiThreadedObservableCollection\fP"
.br
.RI "A MultiThreaedObservableCollection\&. This allows multiple threads to access the same observable collection in a safe manner\&.  "
.ti -1c
.RI "class \fBSaveFile\fP"
.br
.RI "\fBSaveFile\fP  "
.ti -1c
.RI "class \fBSettings\fP"
.br
.RI "\fBSettings\fP  "
.ti -1c
.RI "class \fBSettingsFile\fP"
.br
.ti -1c
.RI "class \fBVersioning\fP"
.br
.ti -1c
.RI "class \fBWindow1\fP"
.br
.RI "\fBWindow1\fP  "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for WolfNet 6502 WorkBench Computer Emulator from the source code\&.
