.TH "Emulator.SettingsFile" 3 "Sat Sep 24 2022" "Version beta" "WolfNet 6502 WorkBench Computer Emulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Emulator.SettingsFile
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBSettingsModel\fP \fBCreateNew\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBSettingsFile\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "static \fBSettingsModel\fP Emulator\&.SettingsFile\&.CreateNew ()\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line \fB8\fP of file \fBSettingsFile\&.cs\fP\&.
.PP
.nf
9         {
10             // Create new settings file\&.
11             SettingsModel _settings = new SettingsModel
12             {
13                 SettingsVersionMajor = Versioning\&.SettingsFile\&.Major,
14                 SettingsVersionMinor = Versioning\&.SettingsFile\&.Minor,
15                 SettingsVersionBuild = Versioning\&.SettingsFile\&.Build,
16                 SettingsVersionRevision = Versioning\&.SettingsFile\&.Revision,
17 #if DEBUG
18                 ComPortName = "COM9",
19 #else
20                 ComPortName = "COM1",
21 #endif
22             };
23             return _settings;
24         }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for WolfNet 6502 WorkBench Computer Emulator from the source code\&.
