.TH "Emulator.Model.MemoryRowModel" 3 "Sat Sep 24 2022" "Version beta" "WolfNet 6502 WorkBench Computer Emulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Emulator.Model.MemoryRowModel \- A \fBModel\fP of a Single Page of memory   

.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBOffset\fP\fC [get, set]\fP"
.br
.RI "The offset of this row\&. Expressed in hex  "
.ti -1c
.RI "string \fBLocation00\fP\fC [get, set]\fP"
.br
.RI "The memory at the location offset + 00  "
.ti -1c
.RI "string \fBLocation01\fP\fC [get, set]\fP"
.br
.RI "The memory at the location offset + 01  "
.ti -1c
.RI "string \fBLocation02\fP\fC [get, set]\fP"
.br
.RI "The memory at the location offset + 02  "
.ti -1c
.RI "string \fBLocation03\fP\fC [get, set]\fP"
.br
.RI "The memory at the location offset + 03  "
.ti -1c
.RI "string \fBLocation04\fP\fC [get, set]\fP"
.br
.RI "The memory at the location offset + 04  "
.ti -1c
.RI "string \fBLocation05\fP\fC [get, set]\fP"
.br
.RI "The memory at the location offset + 05  "
.ti -1c
.RI "string \fBLocation06\fP\fC [get, set]\fP"
.br
.RI "The memory at the location offset + 06  "
.ti -1c
.RI "string \fBLocation07\fP\fC [get, set]\fP"
.br
.RI "The memory at the location offset + 07  "
.ti -1c
.RI "string \fBLocation08\fP\fC [get, set]\fP"
.br
.RI "The memory at the location offset + 08  "
.ti -1c
.RI "string \fBLocation09\fP\fC [get, set]\fP"
.br
.RI "The memory at the location offset + 09  "
.ti -1c
.RI "string \fBLocation0A\fP\fC [get, set]\fP"
.br
.RI "The memory at the location offset + 0A  "
.ti -1c
.RI "string \fBLocation0B\fP\fC [get, set]\fP"
.br
.RI "The memory at the location offset + 0B  "
.ti -1c
.RI "string \fBLocation0C\fP\fC [get, set]\fP"
.br
.RI "The memory at the location offset + 0C  "
.ti -1c
.RI "string \fBLocation0D\fP\fC [get, set]\fP"
.br
.RI "The memory at the location offset + 0D  "
.ti -1c
.RI "string \fBLocation0E\fP\fC [get, set]\fP"
.br
.RI "The memory at the location offset + 0E  "
.ti -1c
.RI "string \fBLocation0F\fP\fC [get, set]\fP"
.br
.RI "The memory at the location offset + 0F  "
.in -1c
.SH "Detailed Description"
.PP 
A \fBModel\fP of a Single Page of memory  
.PP
Definition at line \fB6\fP of file \fBMemoryRowModel\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "string Emulator\&.Model\&.MemoryRowModel\&.Location00\fC [get]\fP, \fC [set]\fP"

.PP
The memory at the location offset + 00  
.PP
Definition at line \fB15\fP of file \fBMemoryRowModel\&.cs\fP\&.
.PP
.nf
15 { get; set; }
.fi
.SS "string Emulator\&.Model\&.MemoryRowModel\&.Location01\fC [get]\fP, \fC [set]\fP"

.PP
The memory at the location offset + 01  
.PP
Definition at line \fB19\fP of file \fBMemoryRowModel\&.cs\fP\&.
.PP
.nf
19 { get; set; }
.fi
.SS "string Emulator\&.Model\&.MemoryRowModel\&.Location02\fC [get]\fP, \fC [set]\fP"

.PP
The memory at the location offset + 02  
.PP
Definition at line \fB23\fP of file \fBMemoryRowModel\&.cs\fP\&.
.PP
.nf
23 { get; set; }
.fi
.SS "string Emulator\&.Model\&.MemoryRowModel\&.Location03\fC [get]\fP, \fC [set]\fP"

.PP
The memory at the location offset + 03  
.PP
Definition at line \fB27\fP of file \fBMemoryRowModel\&.cs\fP\&.
.PP
.nf
27 { get; set; }
.fi
.SS "string Emulator\&.Model\&.MemoryRowModel\&.Location04\fC [get]\fP, \fC [set]\fP"

.PP
The memory at the location offset + 04  
.PP
Definition at line \fB31\fP of file \fBMemoryRowModel\&.cs\fP\&.
.PP
.nf
31 { get; set; }
.fi
.SS "string Emulator\&.Model\&.MemoryRowModel\&.Location05\fC [get]\fP, \fC [set]\fP"

.PP
The memory at the location offset + 05  
.PP
Definition at line \fB35\fP of file \fBMemoryRowModel\&.cs\fP\&.
.PP
.nf
35 { get; set; }
.fi
.SS "string Emulator\&.Model\&.MemoryRowModel\&.Location06\fC [get]\fP, \fC [set]\fP"

.PP
The memory at the location offset + 06  
.PP
Definition at line \fB39\fP of file \fBMemoryRowModel\&.cs\fP\&.
.PP
.nf
39 { get; set; }
.fi
.SS "string Emulator\&.Model\&.MemoryRowModel\&.Location07\fC [get]\fP, \fC [set]\fP"

.PP
The memory at the location offset + 07  
.PP
Definition at line \fB43\fP of file \fBMemoryRowModel\&.cs\fP\&.
.PP
.nf
43 { get; set; }
.fi
.SS "string Emulator\&.Model\&.MemoryRowModel\&.Location08\fC [get]\fP, \fC [set]\fP"

.PP
The memory at the location offset + 08  
.PP
Definition at line \fB47\fP of file \fBMemoryRowModel\&.cs\fP\&.
.PP
.nf
47 { get; set; }
.fi
.SS "string Emulator\&.Model\&.MemoryRowModel\&.Location09\fC [get]\fP, \fC [set]\fP"

.PP
The memory at the location offset + 09  
.PP
Definition at line \fB51\fP of file \fBMemoryRowModel\&.cs\fP\&.
.PP
.nf
51 { get; set; }
.fi
.SS "string Emulator\&.Model\&.MemoryRowModel\&.Location0A\fC [get]\fP, \fC [set]\fP"

.PP
The memory at the location offset + 0A  
.PP
Definition at line \fB55\fP of file \fBMemoryRowModel\&.cs\fP\&.
.PP
.nf
55 { get; set; }
.fi
.SS "string Emulator\&.Model\&.MemoryRowModel\&.Location0B\fC [get]\fP, \fC [set]\fP"

.PP
The memory at the location offset + 0B  
.PP
Definition at line \fB59\fP of file \fBMemoryRowModel\&.cs\fP\&.
.PP
.nf
59 { get; set; }
.fi
.SS "string Emulator\&.Model\&.MemoryRowModel\&.Location0C\fC [get]\fP, \fC [set]\fP"

.PP
The memory at the location offset + 0C  
.PP
Definition at line \fB63\fP of file \fBMemoryRowModel\&.cs\fP\&.
.PP
.nf
63 { get; set; }
.fi
.SS "string Emulator\&.Model\&.MemoryRowModel\&.Location0D\fC [get]\fP, \fC [set]\fP"

.PP
The memory at the location offset + 0D  
.PP
Definition at line \fB67\fP of file \fBMemoryRowModel\&.cs\fP\&.
.PP
.nf
67 { get; set; }
.fi
.SS "string Emulator\&.Model\&.MemoryRowModel\&.Location0E\fC [get]\fP, \fC [set]\fP"

.PP
The memory at the location offset + 0E  
.PP
Definition at line \fB71\fP of file \fBMemoryRowModel\&.cs\fP\&.
.PP
.nf
71 { get; set; }
.fi
.SS "string Emulator\&.Model\&.MemoryRowModel\&.Location0F\fC [get]\fP, \fC [set]\fP"

.PP
The memory at the location offset + 0F  
.PP
Definition at line \fB75\fP of file \fBMemoryRowModel\&.cs\fP\&.
.PP
.nf
75 { get; set; }
.fi
.SS "string Emulator\&.Model\&.MemoryRowModel\&.Offset\fC [get]\fP, \fC [set]\fP"

.PP
The offset of this row\&. Expressed in hex  
.PP
Definition at line \fB11\fP of file \fBMemoryRowModel\&.cs\fP\&.
.PP
.nf
11 { get; set; }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for WolfNet 6502 WorkBench Computer Emulator from the source code\&.
