.TH "Hardware.MemoryMap.Devices.MM65SIB" 3 "Sat Sep 24 2022" "Version beta" "WolfNet 6502 WorkBench Computer Emulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Hardware.MemoryMap.Devices.MM65SIB
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static int \fBLength\fP = 0x0F"
.br
.ti -1c
.RI "static byte \fBOffset\fP = 0x30"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB70\fP of file \fBMemoryMap\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int Hardware\&.MemoryMap\&.Devices\&.MM65SIB\&.Length = 0x0F\fC [static]\fP"

.PP
Definition at line \fB72\fP of file \fBMemoryMap\&.cs\fP\&.
.SS "byte Hardware\&.MemoryMap\&.Devices\&.MM65SIB\&.Offset = 0x30\fC [static]\fP"

.PP
Definition at line \fB73\fP of file \fBMemoryMap\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for WolfNet 6502 WorkBench Computer Emulator from the source code\&.
