.TH "Emulator/obj/x86/Debug/MainWindow.g.cs" 3 "Sat Sep 24 2022" "Version beta" "WolfNet 6502 WorkBench Computer Emulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Emulator/obj/x86/Debug/MainWindow.g.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBEmulator\&.MainWindow\fP"
.br
.RI "Interaction logic for MainWindow\&.xaml  "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBEmulator\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for WolfNet 6502 WorkBench Computer Emulator from the source code\&.
