.TH "Emulator/Model/OutputLog.cs" 3 "Sat Sep 24 2022" "Version beta" "WolfNet 6502 WorkBench Computer Emulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Emulator/Model/OutputLog.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBEmulator\&.Model\&.OutputLog\fP"
.br
.RI "The \fBOutputLog\fP \fBModel\fP\&. Used by the outputlog grid to show a history of operations performed by the CPU  "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBEmulator\fP"
.br
.ti -1c
.RI "namespace \fBEmulator\&.Model\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for WolfNet 6502 WorkBench Computer Emulator from the source code\&.
