.TH "Emulator/ViewModel/ViewModelLocator.cs" 3 "Sat Sep 24 2022" "Version beta" "WolfNet 6502 WorkBench Computer Emulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Emulator/ViewModel/ViewModelLocator.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBEmulator\&.ViewModel\&.ViewModelLocator\fP"
.br
.RI "This class contains static references to all the view models in the application and provides an entry point for the bindings\&.  "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBEmulator\fP"
.br
.ti -1c
.RI "namespace \fBEmulator\&.ViewModel\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for WolfNet 6502 WorkBench Computer Emulator from the source code\&.
