.TH "XamlGeneratedNamespace.GeneratedApplication" 3 "Sat Sep 24 2022" "Version beta" "WolfNet 6502 WorkBench Computer Emulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
XamlGeneratedNamespace.GeneratedApplication \- \fBGeneratedApplication\fP   

.SH SYNOPSIS
.br
.PP
.PP
Inherits System\&.Windows\&.Application, and System\&.Windows\&.Application\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBInitializeComponent\fP ()"
.br
.RI "InitializeComponent  "
.ti -1c
.RI "void \fBInitializeComponent\fP ()"
.br
.RI "InitializeComponent  "
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBMain\fP ()"
.br
.RI "Application Entry Point\&.  "
.ti -1c
.RI "static void \fBMain\fP ()"
.br
.RI "Application Entry Point\&.  "
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "bool \fB_contentLoaded\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBGeneratedApplication\fP  
.PP
Definition at line \fB41\fP of file \fBApp\&.g\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void XamlGeneratedNamespace\&.GeneratedApplication\&.InitializeComponent ()\fC [inline]\fP"

.PP
InitializeComponent  
.PP
Definition at line \fB50\fP of file \fBApp\&.g\&.cs\fP\&.
.PP
.nf
50                                           {
51             if (_contentLoaded) {
52                 return;
53             }
54             _contentLoaded = true;
55             
56             #line 2 "\&.\&.\\&.\&.\\&.\&.\App\&.xaml"
57             this\&.StartupUri = new System\&.Uri("MainWindow\&.xaml", System\&.UriKind\&.Relative);
58             
59             #line default
60             #line hidden
61             System\&.Uri resourceLocater = new System\&.Uri("/Emulator;component/app\&.xaml", System\&.UriKind\&.Relative);
62             
63             #line 1 "\&.\&.\\&.\&.\\&.\&.\App\&.xaml"
64             System\&.Windows\&.Application\&.LoadComponent(this, resourceLocater);
65             
66             #line default
67             #line hidden
68         }
.fi
.SS "void XamlGeneratedNamespace\&.GeneratedApplication\&.InitializeComponent ()\fC [inline]\fP"

.PP
InitializeComponent  
.PP
Definition at line \fB50\fP of file \fBApp\&.g\&.i\&.cs\fP\&.
.PP
.nf
50                                           {
51             if (_contentLoaded) {
52                 return;
53             }
54             _contentLoaded = true;
55             
56             #line 2 "\&.\&.\\&.\&.\\&.\&.\App\&.xaml"
57             this\&.StartupUri = new System\&.Uri("MainWindow\&.xaml", System\&.UriKind\&.Relative);
58             
59             #line default
60             #line hidden
61             System\&.Uri resourceLocater = new System\&.Uri("/Emulator;component/app\&.xaml", System\&.UriKind\&.Relative);
62             
63             #line 1 "\&.\&.\\&.\&.\\&.\&.\App\&.xaml"
64             System\&.Windows\&.Application\&.LoadComponent(this, resourceLocater);
65             
66             #line default
67             #line hidden
68         }
.fi
.SS "static void XamlGeneratedNamespace\&.GeneratedApplication\&.Main ()\fC [inline]\fP, \fC [static]\fP"

.PP
Application Entry Point\&.  
.PP
Definition at line \fB76\fP of file \fBApp\&.g\&.cs\fP\&.
.PP
.nf
76                                   {
77             SplashScreen splashScreen = new SplashScreen("splashscreen\&.png");
78             splashScreen\&.Show(true);
79             XamlGeneratedNamespace\&.GeneratedApplication app = new XamlGeneratedNamespace\&.GeneratedApplication();
80             app\&.InitializeComponent();
81             app\&.Run();
82         }
.fi
.SS "static void XamlGeneratedNamespace\&.GeneratedApplication\&.Main ()\fC [inline]\fP, \fC [static]\fP"

.PP
Application Entry Point\&.  
.PP
Definition at line \fB76\fP of file \fBApp\&.g\&.i\&.cs\fP\&.
.PP
.nf
76                                   {
77             SplashScreen splashScreen = new SplashScreen("splashscreen\&.png");
78             splashScreen\&.Show(true);
79             XamlGeneratedNamespace\&.GeneratedApplication app = new XamlGeneratedNamespace\&.GeneratedApplication();
80             app\&.InitializeComponent();
81             app\&.Run();
82         }
.fi
.SH "Member Data Documentation"
.PP 
.SS "bool XamlGeneratedNamespace\&.GeneratedApplication\&._contentLoaded\fC [private]\fP"

.PP
Definition at line \fB43\fP of file \fBApp\&.g\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for WolfNet 6502 WorkBench Computer Emulator from the source code\&.
