.TH "XamlGeneratedNamespace.GeneratedInternalTypeHelper" 3 "Wed Sep 28 2022" "Version beta" "WolfNet 6502 WorkBench Computer Emulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
XamlGeneratedNamespace.GeneratedInternalTypeHelper \- \fBGeneratedInternalTypeHelper\fP   

.SH SYNOPSIS
.br
.PP
.PP
Inherits System\&.Windows\&.Markup\&.InternalTypeHelper, System\&.Windows\&.Markup\&.InternalTypeHelper, and System\&.Windows\&.Markup\&.InternalTypeHelper\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override object \fBCreateInstance\fP (System\&.Type type, System\&.Globalization\&.CultureInfo culture)"
.br
.RI "CreateInstance  "
.ti -1c
.RI "override object \fBGetPropertyValue\fP (System\&.Reflection\&.PropertyInfo propertyInfo, object target, System\&.Globalization\&.CultureInfo culture)"
.br
.RI "GetPropertyValue  "
.ti -1c
.RI "override void \fBSetPropertyValue\fP (System\&.Reflection\&.PropertyInfo propertyInfo, object target, object value, System\&.Globalization\&.CultureInfo culture)"
.br
.RI "SetPropertyValue  "
.ti -1c
.RI "override System\&.Delegate \fBCreateDelegate\fP (System\&.Type delegateType, object target, string handler)"
.br
.RI "CreateDelegate  "
.ti -1c
.RI "override void \fBAddEventHandler\fP (System\&.Reflection\&.EventInfo eventInfo, object target, System\&.Delegate handler)"
.br
.RI "AddEventHandler  "
.ti -1c
.RI "override object \fBCreateInstance\fP (System\&.Type type, System\&.Globalization\&.CultureInfo culture)"
.br
.RI "CreateInstance  "
.ti -1c
.RI "override object \fBGetPropertyValue\fP (System\&.Reflection\&.PropertyInfo propertyInfo, object target, System\&.Globalization\&.CultureInfo culture)"
.br
.RI "GetPropertyValue  "
.ti -1c
.RI "override void \fBSetPropertyValue\fP (System\&.Reflection\&.PropertyInfo propertyInfo, object target, object value, System\&.Globalization\&.CultureInfo culture)"
.br
.RI "SetPropertyValue  "
.ti -1c
.RI "override System\&.Delegate \fBCreateDelegate\fP (System\&.Type delegateType, object target, string handler)"
.br
.RI "CreateDelegate  "
.ti -1c
.RI "override void \fBAddEventHandler\fP (System\&.Reflection\&.EventInfo eventInfo, object target, System\&.Delegate handler)"
.br
.RI "AddEventHandler  "
.ti -1c
.RI "override object \fBCreateInstance\fP (System\&.Type type, System\&.Globalization\&.CultureInfo culture)"
.br
.RI "CreateInstance  "
.ti -1c
.RI "override object \fBGetPropertyValue\fP (System\&.Reflection\&.PropertyInfo propertyInfo, object target, System\&.Globalization\&.CultureInfo culture)"
.br
.RI "GetPropertyValue  "
.ti -1c
.RI "override void \fBSetPropertyValue\fP (System\&.Reflection\&.PropertyInfo propertyInfo, object target, object value, System\&.Globalization\&.CultureInfo culture)"
.br
.RI "SetPropertyValue  "
.ti -1c
.RI "override System\&.Delegate \fBCreateDelegate\fP (System\&.Type delegateType, object target, string handler)"
.br
.RI "CreateDelegate  "
.ti -1c
.RI "override void \fBAddEventHandler\fP (System\&.Reflection\&.EventInfo eventInfo, object target, System\&.Delegate handler)"
.br
.RI "AddEventHandler  "
.in -1c
.SH "Detailed Description"
.PP 
\fBGeneratedInternalTypeHelper\fP  
.PP
Definition at line \fB20\fP of file \fBGeneratedInternalTypeHelper\&.g\&.i\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void XamlGeneratedNamespace\&.GeneratedInternalTypeHelper\&.AddEventHandler (System\&.Reflection\&.EventInfo eventInfo, object target, System\&.Delegate handler)\fC [inline]\fP, \fC [protected]\fP"

.PP
AddEventHandler  
.PP
Definition at line \fB57\fP of file \fBGeneratedInternalTypeHelper\&.g\&.i\&.cs\fP\&.
.PP
.nf
57                                                                                                                                {
58             eventInfo\&.AddEventHandler(target, handler);
59         }
.fi
.SS "override void XamlGeneratedNamespace\&.GeneratedInternalTypeHelper\&.AddEventHandler (System\&.Reflection\&.EventInfo eventInfo, object target, System\&.Delegate handler)\fC [inline]\fP, \fC [protected]\fP"

.PP
AddEventHandler  
.PP
Definition at line \fB57\fP of file \fBGeneratedInternalTypeHelper\&.g\&.i\&.cs\fP\&.
.PP
.nf
57                                                                                                                                {
58             eventInfo\&.AddEventHandler(target, handler);
59         }
.fi
.SS "override void XamlGeneratedNamespace\&.GeneratedInternalTypeHelper\&.AddEventHandler (System\&.Reflection\&.EventInfo eventInfo, object target, System\&.Delegate handler)\fC [inline]\fP, \fC [protected]\fP"

.PP
AddEventHandler  
.PP
Definition at line \fB57\fP of file \fBGeneratedInternalTypeHelper\&.g\&.i\&.cs\fP\&.
.PP
.nf
57                                                                                                                                {
58             eventInfo\&.AddEventHandler(target, handler);
59         }
.fi
.SS "override System\&.Delegate XamlGeneratedNamespace\&.GeneratedInternalTypeHelper\&.CreateDelegate (System\&.Type delegateType, object target, string handler)\fC [inline]\fP, \fC [protected]\fP"

.PP
CreateDelegate  
.PP
Definition at line \fB47\fP of file \fBGeneratedInternalTypeHelper\&.g\&.i\&.cs\fP\&.
.PP
.nf
47                                                                                                                    {
48             return ((System\&.Delegate)(target\&.GetType()\&.InvokeMember("_CreateDelegate", (System\&.Reflection\&.BindingFlags\&.InvokeMethod 
49                             | (System\&.Reflection\&.BindingFlags\&.NonPublic | System\&.Reflection\&.BindingFlags\&.Instance)), null, target, new object[] {
50                         delegateType,
51                         handler}, null)));
52         }
.fi
.SS "override System\&.Delegate XamlGeneratedNamespace\&.GeneratedInternalTypeHelper\&.CreateDelegate (System\&.Type delegateType, object target, string handler)\fC [inline]\fP, \fC [protected]\fP"

.PP
CreateDelegate  
.PP
Definition at line \fB47\fP of file \fBGeneratedInternalTypeHelper\&.g\&.i\&.cs\fP\&.
.PP
.nf
47                                                                                                                    {
48             return ((System\&.Delegate)(target\&.GetType()\&.InvokeMember("_CreateDelegate", (System\&.Reflection\&.BindingFlags\&.InvokeMethod 
49                             | (System\&.Reflection\&.BindingFlags\&.NonPublic | System\&.Reflection\&.BindingFlags\&.Instance)), null, target, new object[] {
50                         delegateType,
51                         handler}, null)));
52         }
.fi
.SS "override System\&.Delegate XamlGeneratedNamespace\&.GeneratedInternalTypeHelper\&.CreateDelegate (System\&.Type delegateType, object target, string handler)\fC [inline]\fP, \fC [protected]\fP"

.PP
CreateDelegate  
.PP
Definition at line \fB47\fP of file \fBGeneratedInternalTypeHelper\&.g\&.i\&.cs\fP\&.
.PP
.nf
47                                                                                                                    {
48             return ((System\&.Delegate)(target\&.GetType()\&.InvokeMember("_CreateDelegate", (System\&.Reflection\&.BindingFlags\&.InvokeMethod 
49                             | (System\&.Reflection\&.BindingFlags\&.NonPublic | System\&.Reflection\&.BindingFlags\&.Instance)), null, target, new object[] {
50                         delegateType,
51                         handler}, null)));
52         }
.fi
.SS "override object XamlGeneratedNamespace\&.GeneratedInternalTypeHelper\&.CreateInstance (System\&.Type type, System\&.Globalization\&.CultureInfo culture)\fC [inline]\fP, \fC [protected]\fP"

.PP
CreateInstance  
.PP
Definition at line \fB25\fP of file \fBGeneratedInternalTypeHelper\&.g\&.i\&.cs\fP\&.
.PP
.nf
25                                                                                                              {
26             return System\&.Activator\&.CreateInstance(type, ((System\&.Reflection\&.BindingFlags\&.Public | System\&.Reflection\&.BindingFlags\&.NonPublic) 
27                             | (System\&.Reflection\&.BindingFlags\&.Instance | System\&.Reflection\&.BindingFlags\&.CreateInstance)), null, null, culture);
28         }
.fi
.SS "override object XamlGeneratedNamespace\&.GeneratedInternalTypeHelper\&.CreateInstance (System\&.Type type, System\&.Globalization\&.CultureInfo culture)\fC [inline]\fP, \fC [protected]\fP"

.PP
CreateInstance  
.PP
Definition at line \fB25\fP of file \fBGeneratedInternalTypeHelper\&.g\&.i\&.cs\fP\&.
.PP
.nf
25                                                                                                              {
26             return System\&.Activator\&.CreateInstance(type, ((System\&.Reflection\&.BindingFlags\&.Public | System\&.Reflection\&.BindingFlags\&.NonPublic) 
27                             | (System\&.Reflection\&.BindingFlags\&.Instance | System\&.Reflection\&.BindingFlags\&.CreateInstance)), null, null, culture);
28         }
.fi
.SS "override object XamlGeneratedNamespace\&.GeneratedInternalTypeHelper\&.CreateInstance (System\&.Type type, System\&.Globalization\&.CultureInfo culture)\fC [inline]\fP, \fC [protected]\fP"

.PP
CreateInstance  
.PP
Definition at line \fB25\fP of file \fBGeneratedInternalTypeHelper\&.g\&.i\&.cs\fP\&.
.PP
.nf
25                                                                                                              {
26             return System\&.Activator\&.CreateInstance(type, ((System\&.Reflection\&.BindingFlags\&.Public | System\&.Reflection\&.BindingFlags\&.NonPublic) 
27                             | (System\&.Reflection\&.BindingFlags\&.Instance | System\&.Reflection\&.BindingFlags\&.CreateInstance)), null, null, culture);
28         }
.fi
.SS "override object XamlGeneratedNamespace\&.GeneratedInternalTypeHelper\&.GetPropertyValue (System\&.Reflection\&.PropertyInfo propertyInfo, object target, System\&.Globalization\&.CultureInfo culture)\fC [inline]\fP, \fC [protected]\fP"

.PP
GetPropertyValue  
.PP
Definition at line \fB33\fP of file \fBGeneratedInternalTypeHelper\&.g\&.i\&.cs\fP\&.
.PP
.nf
33                                                                                                                                                          {
34             return propertyInfo\&.GetValue(target, System\&.Reflection\&.BindingFlags\&.Default, null, null, culture);
35         }
.fi
.SS "override object XamlGeneratedNamespace\&.GeneratedInternalTypeHelper\&.GetPropertyValue (System\&.Reflection\&.PropertyInfo propertyInfo, object target, System\&.Globalization\&.CultureInfo culture)\fC [inline]\fP, \fC [protected]\fP"

.PP
GetPropertyValue  
.PP
Definition at line \fB33\fP of file \fBGeneratedInternalTypeHelper\&.g\&.i\&.cs\fP\&.
.PP
.nf
33                                                                                                                                                          {
34             return propertyInfo\&.GetValue(target, System\&.Reflection\&.BindingFlags\&.Default, null, null, culture);
35         }
.fi
.SS "override object XamlGeneratedNamespace\&.GeneratedInternalTypeHelper\&.GetPropertyValue (System\&.Reflection\&.PropertyInfo propertyInfo, object target, System\&.Globalization\&.CultureInfo culture)\fC [inline]\fP, \fC [protected]\fP"

.PP
GetPropertyValue  
.PP
Definition at line \fB33\fP of file \fBGeneratedInternalTypeHelper\&.g\&.i\&.cs\fP\&.
.PP
.nf
33                                                                                                                                                          {
34             return propertyInfo\&.GetValue(target, System\&.Reflection\&.BindingFlags\&.Default, null, null, culture);
35         }
.fi
.SS "override void XamlGeneratedNamespace\&.GeneratedInternalTypeHelper\&.SetPropertyValue (System\&.Reflection\&.PropertyInfo propertyInfo, object target, object value, System\&.Globalization\&.CultureInfo culture)\fC [inline]\fP, \fC [protected]\fP"

.PP
SetPropertyValue  
.PP
Definition at line \fB40\fP of file \fBGeneratedInternalTypeHelper\&.g\&.i\&.cs\fP\&.
.PP
.nf
40                                                                                                                                                                      {
41             propertyInfo\&.SetValue(target, value, System\&.Reflection\&.BindingFlags\&.Default, null, null, culture);
42         }
.fi
.SS "override void XamlGeneratedNamespace\&.GeneratedInternalTypeHelper\&.SetPropertyValue (System\&.Reflection\&.PropertyInfo propertyInfo, object target, object value, System\&.Globalization\&.CultureInfo culture)\fC [inline]\fP, \fC [protected]\fP"

.PP
SetPropertyValue  
.PP
Definition at line \fB40\fP of file \fBGeneratedInternalTypeHelper\&.g\&.i\&.cs\fP\&.
.PP
.nf
40                                                                                                                                                                      {
41             propertyInfo\&.SetValue(target, value, System\&.Reflection\&.BindingFlags\&.Default, null, null, culture);
42         }
.fi
.SS "override void XamlGeneratedNamespace\&.GeneratedInternalTypeHelper\&.SetPropertyValue (System\&.Reflection\&.PropertyInfo propertyInfo, object target, object value, System\&.Globalization\&.CultureInfo culture)\fC [inline]\fP, \fC [protected]\fP"

.PP
SetPropertyValue  
.PP
Definition at line \fB40\fP of file \fBGeneratedInternalTypeHelper\&.g\&.i\&.cs\fP\&.
.PP
.nf
40                                                                                                                                                                      {
41             propertyInfo\&.SetValue(target, value, System\&.Reflection\&.BindingFlags\&.Default, null, null, culture);
42         }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for WolfNet 6502 WorkBench Computer Emulator from the source code\&.
