.TH "Emulator/Classes Directory Reference" 3 "Wed Sep 28 2022" "Version beta" "WolfNet 6502 WorkBench Computer Emulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Emulator/Classes Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBExitCodes\&.cs\fP"
.br
.ti -1c
.RI "file \fBFileLocations\&.cs\fP"
.br
.ti -1c
.RI "file \fBSettingsFile\&.cs\fP"
.br
.ti -1c
.RI "file \fBVersioning\&.cs\fP"
.br
.in -1c
