.TH "Emulator.Model.SettingsModel" 3 "Wed Sep 28 2022" "Version beta" "WolfNet 6502 WorkBench Computer Emulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Emulator.Model.SettingsModel \- \fBModel\fP that contains the required information needed to save the current settings to disk   

.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "byte \fBSettingsVersionMajor\fP\fC [get, set]\fP"
.br
.RI "The version of the file that is being saved  "
.ti -1c
.RI "byte \fBSettingsVersionMinor\fP\fC [get, set]\fP"
.br
.RI "The version of the file that is being saved  "
.ti -1c
.RI "byte \fBSettingsVersionBuild\fP\fC [get, set]\fP"
.br
.RI "The version of the file that is being saved  "
.ti -1c
.RI "byte \fBSettingsVersionRevision\fP\fC [get, set]\fP"
.br
.RI "The version of the file that is being saved  "
.ti -1c
.RI "string \fBComPortName\fP\fC [get, set]\fP"
.br
.RI "The PC port that is being saved  "
.in -1c
.SH "Detailed Description"
.PP 
\fBModel\fP that contains the required information needed to save the current settings to disk  
.PP
Definition at line \fB11\fP of file \fBSettingsModel\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "string Emulator\&.Model\&.SettingsModel\&.ComPortName\fC [get]\fP, \fC [set]\fP"

.PP
The PC port that is being saved  
.PP
Definition at line \fB36\fP of file \fBSettingsModel\&.cs\fP\&.
.PP
.nf
36 { get; set; }
.fi
.SS "byte Emulator\&.Model\&.SettingsModel\&.SettingsVersionBuild\fC [get]\fP, \fC [set]\fP"

.PP
The version of the file that is being saved  
.PP
Definition at line \fB26\fP of file \fBSettingsModel\&.cs\fP\&.
.PP
.nf
26 { get; set; }
.fi
.SS "byte Emulator\&.Model\&.SettingsModel\&.SettingsVersionMajor\fC [get]\fP, \fC [set]\fP"

.PP
The version of the file that is being saved  
.PP
Definition at line \fB16\fP of file \fBSettingsModel\&.cs\fP\&.
.PP
.nf
16 { get; set; }
.fi
.SS "byte Emulator\&.Model\&.SettingsModel\&.SettingsVersionMinor\fC [get]\fP, \fC [set]\fP"

.PP
The version of the file that is being saved  
.PP
Definition at line \fB21\fP of file \fBSettingsModel\&.cs\fP\&.
.PP
.nf
21 { get; set; }
.fi
.SS "byte Emulator\&.Model\&.SettingsModel\&.SettingsVersionRevision\fC [get]\fP, \fC [set]\fP"

.PP
The version of the file that is being saved  
.PP
Definition at line \fB31\fP of file \fBSettingsModel\&.cs\fP\&.
.PP
.nf
31 { get; set; }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for WolfNet 6502 WorkBench Computer Emulator from the source code\&.
