.TH "Emulator.Versioning.SettingsFile" 3 "Wed Sep 28 2022" "Version beta" "WolfNet 6502 WorkBench Computer Emulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Emulator.Versioning.SettingsFile
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "const byte \fBMajor\fP = 1"
.br
.ti -1c
.RI "const byte \fBMinor\fP = 0"
.br
.ti -1c
.RI "const byte \fBBuild\fP = 0"
.br
.ti -1c
.RI "const byte \fBRevision\fP = 0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB18\fP of file \fBVersioning\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "const byte Emulator\&.Versioning\&.SettingsFile\&.Build = 0\fC [static]\fP"

.PP
Definition at line \fB22\fP of file \fBVersioning\&.cs\fP\&.
.SS "const byte Emulator\&.Versioning\&.SettingsFile\&.Major = 1\fC [static]\fP"

.PP
Definition at line \fB20\fP of file \fBVersioning\&.cs\fP\&.
.SS "const byte Emulator\&.Versioning\&.SettingsFile\&.Minor = 0\fC [static]\fP"

.PP
Definition at line \fB21\fP of file \fBVersioning\&.cs\fP\&.
.SS "const byte Emulator\&.Versioning\&.SettingsFile\&.Revision = 0\fC [static]\fP"

.PP
Definition at line \fB23\fP of file \fBVersioning\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for WolfNet 6502 WorkBench Computer Emulator from the source code\&.
