.TH "Emulator.App" 3 "Wed Sep 28 2022" "Version beta" "WolfNet 6502 WorkBench Computer Emulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Emulator.App \- Interaction logic for App\&.xaml   

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Interaction logic for App\&.xaml  
.PP
Definition at line \fB6\fP of file \fBApp\&.xaml\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for WolfNet 6502 WorkBench Computer Emulator from the source code\&.
