.TH "Emulator.Window1" 3 "Wed Sep 28 2022" "Version beta" "WolfNet 6502 WorkBench Computer Emulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Emulator.Window1 \- \fBWindow1\fP   

.SH SYNOPSIS
.br
.PP
.PP
Inherits System\&.Windows\&.Window, System\&.Windows\&.Markup\&.IComponentConnector, System\&.Windows\&.Window, and System\&.Windows\&.Markup\&.IComponentConnector\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBInitializeComponent\fP ()"
.br
.RI "InitializeComponent  "
.ti -1c
.RI "void \fBInitializeComponent\fP ()"
.br
.RI "InitializeComponent  "
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void System\&.Windows\&.Markup\&.IComponentConnector\&. \fBConnect\fP (int connectionId, object target)"
.br
.ti -1c
.RI "void System\&.Windows\&.Markup\&.IComponentConnector\&. \fBConnect\fP (int connectionId, object target)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "bool \fB_contentLoaded\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBWindow1\fP  
.PP
Definition at line \fB41\fP of file \fBMemoryMap\&.g\&.i\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void System\&.Windows\&.Markup\&.IComponentConnector\&. Emulator\&.Window1\&.Connect (int connectionId, object target)\fC [inline]\fP, \fC [private]\fP"

.PP
Definition at line \fB78\fP of file \fBMemoryMap\&.g\&.i\&.cs\fP\&.
.PP
.nf
78                                                                                                 {
79             switch (connectionId)
80             {
81             case 1:
82             this\&.MemoryMap = ((System\&.Windows\&.Controls\&.DataGrid)(target));
83             return;
84             }
85             this\&._contentLoaded = true;
86         }
.fi
.SS "void System\&.Windows\&.Markup\&.IComponentConnector\&. Emulator\&.Window1\&.Connect (int connectionId, object target)\fC [inline]\fP, \fC [private]\fP"

.PP
Definition at line \fB75\fP of file \fBWindow1\&.g\&.i\&.cs\fP\&.
.PP
.nf
76         {
77             this\&._contentLoaded = true;
78         }
.fi
.SS "void Emulator\&.Window1\&.InitializeComponent ()\fC [inline]\fP"

.PP
InitializeComponent  
.PP
Definition at line \fB58\fP of file \fBMemoryMap\&.g\&.i\&.cs\fP\&.
.PP
.nf
58                                           {
59             if (_contentLoaded) {
60                 return;
61             }
62             _contentLoaded = true;
63             System\&.Uri resourceLocater = new System\&.Uri("/Emulator;component/memorymap\&.xaml", System\&.UriKind\&.Relative);
64             
65             #line 1 "\&.\&.\\&.\&.\\&.\&.\MemoryMap\&.xaml"
66             System\&.Windows\&.Application\&.LoadComponent(this, resourceLocater);
67             
68             #line default
69             #line hidden
70         }
.fi
.SS "void Emulator\&.Window1\&.InitializeComponent ()\fC [inline]\fP"

.PP
InitializeComponent  
.PP
Definition at line \fB53\fP of file \fBWindow1\&.g\&.i\&.cs\fP\&.
.PP
.nf
54         {
55             if (_contentLoaded)
56             {
57                 return;
58             }
59             _contentLoaded = true;
60             System\&.Uri resourceLocater = new System\&.Uri("/Emulator;component/window1\&.xaml", System\&.UriKind\&.Relative);
61 
62 #line 1 "\&.\&.\\&.\&.\\&.\&.\Window1\&.xaml"
63             System\&.Windows\&.Application\&.LoadComponent(this, resourceLocater);
64 
65 #line default
66 #line hidden
67         }
.fi
.SH "Member Data Documentation"
.PP 
.SS "bool Emulator\&.Window1\&._contentLoaded\fC [private]\fP"

.PP
Definition at line \fB51\fP of file \fBMemoryMap\&.g\&.i\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for WolfNet 6502 WorkBench Computer Emulator from the source code\&.
