.TH "Emulator.SettingsFile" 3 "Wed Sep 28 2022" "Version beta" "WolfNet 6502 WorkBench Computer Emulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Emulator.SettingsFile
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBSettingsModel\fP \fBCreateNew\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBSettingsFile\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "static \fBSettingsModel\fP Emulator\&.SettingsFile\&.CreateNew ()\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line \fB7\fP of file \fBSettingsFile\&.cs\fP\&.
.PP
.nf
8         {
9             // Create new settings file\&.
10             SettingsModel _settings = new SettingsModel
11             {
12                 SettingsVersionMajor = Versioning\&.SettingsFile\&.Major,
13                 SettingsVersionMinor = Versioning\&.SettingsFile\&.Minor,
14                 SettingsVersionBuild = Versioning\&.SettingsFile\&.Build,
15                 SettingsVersionRevision = Versioning\&.SettingsFile\&.Revision,
16 #if DEBUG
17                 ComPortName = "COM9",
18 #else
19                 ComPortName = "COM1",
20 #endif
21             };
22             return _settings;
23         }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for WolfNet 6502 WorkBench Computer Emulator from the source code\&.
