.TH "Hardware.MemoryMap.SharedRom" 3 "Wed Sep 28 2022" "Version beta" "WolfNet 6502 WorkBench Computer Emulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Hardware.MemoryMap.SharedRom
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static byte \fBTotalBanks\fP = 1"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "static int \fBOffset\fP\fC [get]\fP"
.br
.ti -1c
.RI "static int \fBLength\fP\fC [get]\fP"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static int \fB_Offset\fP = 0xE000"
.br
.ti -1c
.RI "static int \fB_Length\fP = 0x1FFF"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB44\fP of file \fBMemoryMap\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int Hardware\&.MemoryMap\&.SharedRom\&._Length = 0x1FFF\fC [static]\fP, \fC [private]\fP"

.PP
Definition at line \fB47\fP of file \fBMemoryMap\&.cs\fP\&.
.SS "int Hardware\&.MemoryMap\&.SharedRom\&._Offset = 0xE000\fC [static]\fP, \fC [private]\fP"

.PP
Definition at line \fB46\fP of file \fBMemoryMap\&.cs\fP\&.
.SS "byte Hardware\&.MemoryMap\&.SharedRom\&.TotalBanks = 1\fC [static]\fP"

.PP
Definition at line \fB49\fP of file \fBMemoryMap\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "int Hardware\&.MemoryMap\&.SharedRom\&.Length\fC [static]\fP, \fC [get]\fP"

.PP
Definition at line \fB52\fP of file \fBMemoryMap\&.cs\fP\&.
.PP
.nf
52 { get { return _Length; } }
.fi
.SS "int Hardware\&.MemoryMap\&.SharedRom\&.Offset\fC [static]\fP, \fC [get]\fP"

.PP
Definition at line \fB51\fP of file \fBMemoryMap\&.cs\fP\&.
.PP
.nf
51 { get { return _Offset; } }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for WolfNet 6502 WorkBench Computer Emulator from the source code\&.
