.TH "Hardware.Disassembly" 3 "Wed Sep 28 2022" "Version beta" "WolfNet 6502 WorkBench Computer Emulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Hardware.Disassembly \- Used to help simulating\&. This class contains the disassembly properties\&.   

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBEmulator\&.Model\&.OutputLog\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBLowAddress\fP\fC [get, set]\fP"
.br
.RI "The low Address  "
.ti -1c
.RI "string \fBHighAddress\fP\fC [get, set]\fP"
.br
.RI "The High Address  "
.ti -1c
.RI "string \fBOpCodeString\fP\fC [get, set]\fP"
.br
.RI "The string representation of the OpCode  "
.ti -1c
.RI "string \fBDisassemblyOutput\fP\fC [get, set]\fP"
.br
.RI "The disassembly of the current step  "
.in -1c
.SH "Detailed Description"
.PP 
Used to help simulating\&. This class contains the disassembly properties\&.  
.PP
Definition at line \fB9\fP of file \fBDisassembly\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "string Hardware\&.Disassembly\&.DisassemblyOutput\fC [get]\fP, \fC [set]\fP"

.PP
The disassembly of the current step  
.PP
Definition at line \fB29\fP of file \fBDisassembly\&.cs\fP\&.
.PP
.nf
29 { get; set; }
.fi
.SS "string Hardware\&.Disassembly\&.HighAddress\fC [get]\fP, \fC [set]\fP"

.PP
The High Address  
.PP
Definition at line \fB19\fP of file \fBDisassembly\&.cs\fP\&.
.PP
.nf
19 { get; set; }
.fi
.SS "string Hardware\&.Disassembly\&.LowAddress\fC [get]\fP, \fC [set]\fP"

.PP
The low Address  
.PP
Definition at line \fB14\fP of file \fBDisassembly\&.cs\fP\&.
.PP
.nf
14 { get; set; }
.fi
.SS "string Hardware\&.Disassembly\&.OpCodeString\fC [get]\fP, \fC [set]\fP"

.PP
The string representation of the OpCode  
.PP
Definition at line \fB24\fP of file \fBDisassembly\&.cs\fP\&.
.PP
.nf
24 { get; set; }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for WolfNet 6502 WorkBench Computer Emulator from the source code\&.
