.TH "Emulator/ViewModel/MainViewModel.cs" 3 "Wed Sep 28 2022" "Version beta" "WolfNet 6502 WorkBench Computer Emulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Emulator/ViewModel/MainViewModel.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBEmulator\&.ViewModel\&.MainViewModel\fP"
.br
.RI "The Main \fBViewModel\fP  "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBEmulator\fP"
.br
.ti -1c
.RI "namespace \fBEmulator\&.ViewModel\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBW65C02\fP = \fBHardware\&.W65C02\fP"
.br
.ti -1c
.RI "using \fBW65C22\fP = \fBHardware\&.W65C22\fP"
.br
.ti -1c
.RI "using \fBW65C51\fP = \fBHardware\&.W65C51\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "using \fBW65C02\fP =  \fBHardware\&.W65C02\fP"

.PP
Definition at line \fB17\fP of file \fBMainViewModel\&.cs\fP\&.
.SS "using \fBW65C22\fP =  \fBHardware\&.W65C22\fP"

.PP
Definition at line \fB18\fP of file \fBMainViewModel\&.cs\fP\&.
.SS "using \fBW65C51\fP =  \fBHardware\&.W65C51\fP"

.PP
Definition at line \fB19\fP of file \fBMainViewModel\&.cs\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for WolfNet 6502 WorkBench Computer Emulator from the source code\&.
