.TH "Emulator/Model/SettingsModel.cs" 3 "Wed Sep 28 2022" "Version beta" "WolfNet 6502 WorkBench Computer Emulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Emulator/Model/SettingsModel.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBEmulator\&.Model\&.SettingsModel\fP"
.br
.RI "\fBModel\fP that contains the required information needed to save the current settings to disk  "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBEmulator\fP"
.br
.ti -1c
.RI "namespace \fBEmulator\&.Model\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for WolfNet 6502 WorkBench Computer Emulator from the source code\&.
