.TH "XamlGeneratedNamespace" 3 "Wed Sep 28 2022" "Version beta" "WolfNet 6502 WorkBench Computer Emulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
XamlGeneratedNamespace
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGeneratedApplication\fP"
.br
.RI "\fBGeneratedApplication\fP  "
.ti -1c
.RI "class \fBGeneratedInternalTypeHelper\fP"
.br
.RI "\fBGeneratedInternalTypeHelper\fP  "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for WolfNet 6502 WorkBench Computer Emulator from the source code\&.
